### ISSUE TITLE
Frog builds failing for 6.1 and 6.1.1

### ISSUE THREAD

**Issue by greghendershott** [AlexKnauth/reprovide-lang#10]
Travis alerted me that a CRON job for Frog failed for 6.1 and 6.1.1. For example:

  https://travis-ci.org/greghendershott/frog/jobs/457145759#L491-L495

**Comment by greghendershott** [comment]
In your own `.travis.yml`, I'm curious, instead of commit https://github.com/AlexKnauth/reprovide-lang/commit/e55b0ae8bd684899737480f740c4a27976d78a75 deleting older versions why not keep the older versions so you can exercise the version exception thing?

**Comment by AlexKnauth** [comment]
Oh, I think this is due to the "new" package-source syntax of `https://github.com/user/repo.git` not being supported on older versions of Racket. I should use `git://github.com/user/repo` instead.

**Comment by AlexKnauth** [comment]
(Re: In your own `.travis.yml`) The Travis builds don't go through the package catalog to resolve "the package itself", only to resolve dependencies. That's why I can't use it as-is to exercise the version exceptions.

**Comment by greghendershott** [comment]
Oh right -- good thinking!

**Comment by AlexKnauth** [comment]
Is the build working now? After changing the version exceptions in the package catalog, I tried installing through the package catalog name on 6.0 and it worked.

**Comment by greghendershott** [comment]
[Yes](https://travis-ci.org/greghendershott/frog/jobs/457145759) and [yes](https://travis-ci.org/greghendershott/frog/jobs/457145760) -- thanks!!!
