### ISSUE TITLE
Keyword shorthand for `except-in`

### ISSUE THREAD

**Issue by jackfirth** [AlexKnauth/reprovide-lang#3]
Instead of this:

``` racket
#lang reprovide
(except-in
  (combine-in "foo.rkt" "bar.rkt" "baz.rkt")
  secret-foo
  secret-bar
  secret-baz)
```

It would be nice to write this:

``` racket
#lang reprovide
"foo.rkt"
"bar.rkt"
"baz.rkt"
(#:except secret-foo secret-bar secret-baz)
```

Especially if it worked well with sweet-expressions:

``` racket
#lang sweet-exp reprovide
"foo.rkt"
"bar.rkt"
"baz.rkt"
#:except
  secret-foo
  secret-bar
  secret-baz
```

**Comment by AlexKnauth** [comment]
I don't think there should be a special case for this, because I want this to support exactly the syntax for `require`. If you define a require form that does this though, (I mean one that can be used inside of require) I would add support for that.

**Comment by jackfirth** [comment]
`reprovide` is still a superset of the `require` syntax, in that both ways work. If this package is meant to be sugar for making reprovide-modules as simple to write as possible, I think this would be a reasonable feature.

**Comment by AlexKnauth** [comment]
With https://github.com/AlexKnauth/reprovide-lang/pull/4, you would be able to do this:

``` racket
#lang sweet-exp reprovide
combine-in*
  "foo.rkt"
  "bar.rkt"
  "baz.rkt"
  #:except
    secret-foo
    secret-bar
    secret-baz
```

Is that good enough?

**Comment by jackfirth** [comment]
Yes, that works well enough.
