### ISSUE TITLE
REPL diagnostics?

### ISSUE THREAD

**Issue by jackfirth** [AlexKnauth/reprovide-lang#5]
Sometimes I want to see if a binding exists or not in a reprovide module, but since there's no `#%top-interaction` I can't use the repl.

There's interesting space to play with here - reprovide could provide a main module that prints a message and a repl that gives you some commands to do things, like list all exported bindings, list all bindings exported from a specific source module, say where a binding came from, stuff like that. That's probably more work than it's worth though.

**Comment by AlexKnauth** [comment]
Ok, I just added `#%top-interaction`. When I run modules with reprovide, I normally don't want to see something like a list of bindings. However, this gave me another idea, do you think it would be possible for `#lang reprovide` modules to export a `test` submodule that runs the test submodules (if they exist) of the required files? Maybe that's for another issue though. 

(Update: see https://github.com/AlexKnauth/reprovide-lang/issues/6)
