### ISSUE TITLE
Test submod to run tests of reprovided modules?

### ISSUE THREAD

**Issue by AlexKnauth** [AlexKnauth/reprovide-lang#6]
Would be possible for `#lang reprovide` modules to add a test submodule that runs the test submodules (if they exist) of the required files?

**Comment by jackfirth** [comment]
This can cause a cascade of test rerunning if there's reprovide modules that require reprovide modules that require reprovide modules etc., as running `raco test .` will run cause the leaf modules to get run several times.

**Comment by AlexKnauth** [comment]
Maybe a `main` submodule then? I was thinking of it because that's usually what I want when I run one of these reprovide files in DrRacket.

**Comment by jackfirth** [comment]
That makes more sense. Would it be better to require it explicitly at the repl than do it by default? Like have the main submodule define a `test-all` function.
