### ISSUE TITLE
Should also reprovide indirect provides as well

### ISSUE THREAD

**Issue by LeifAndersen** [AlexKnauth/reprovide-lang#8]
If I define a module `A.rkt`, and have it provide `a`. I can then require it from `B.rkt`, and have it provide the new identifier `b`, as well as reprovide `a` from the old module. If I then go into C.rkt, and do:

```
(reprovide "B.rkt")
```

The module does require both `a` and `b`, but only provides `b`.

**Comment by AlexKnauth** [comment]
I'll have to test it myself later; are you saying that currently this doesn't work:
```racket
;; A.rkt
#lang racket
(provide a)
(define a 1)

;; B.rkt
#lang racket
(require reprovide/reprovide)
(reprovide "A.rkt")
(provide b)
(define b 2)

;; C.rkt
#lang racket
(require reprovide/reprovide)
(reprovide "B.rkt")

;; D.rkt
#lang racket
(require "C.rkt")
a
```
?

**Comment by LeifAndersen** [comment]
More or less, but for whatever reason that seems to work:

```
#lang scratch

(module A racket
  (provide a)
  (define a 1))

(module B racket
  (require (submod ".." A))
  (provide a b)
  (define b 2))

(module C racket
  (require reprovide/reprovide)
  (reprovide (submod ".." B)))

(module D racket
  (require (submod ".." C))
  a)
```

However, what doesn't work:

```
;; A.rkt
#lang scribble/manual
(require reprovide/reprovide)
(reprovide scribble/manual)

;; B.scrbl
#lang reader "A-lang.rkt"
```

It will yell at you saying that `#%module-begin` is not defined. You end up having to do:

```
(reprovide scribble/manual/lang)
```

to get module begin.

**Comment by AlexKnauth** [comment]
I'm confused. Does `#lang scribble/manual` expand using `scribble/manual` as the module language, or `scribble/manual/lang`?

(Edit: It uses `scribble/manual/lang`. The `scribble/manual` module doesn't provide a `#%module-begin` itself.)

**Comment by AlexKnauth** [comment]
Is it the same error you get when you try this?
```racket
(module anonymous-module scribble/manual
  doc)
```

This doesn't seem to be `reprovide`'s fault. All the examples I'm trying seem to be working as expected. `"C.rkt"` is providing both `a` and `b` properly, and your scribble-based language doesn't reprovide `#%module-begin` because `scribble/manual` (the module) never provided that to begin with. It makes sense that you have to reprovide from `scribble/manual/lang`, since that's the actual module language that scribble's `#lang` uses.

**Comment by LeifAndersen** [comment]
Ya, I agree. Its kind of odd, but I suspect the scribble reader is doing something here, which as you said, is not reprovide's fault...but scribble's. ;)
